apiVersion: v1
kind: kbrew
app:
  repository:
    name: jetstack
    url: https://charts.jetstack.io
    type: helm
  namespace: cert-manager
  sha256:
  version: v1.3.1
  pre_install:
  - steps:
    - kubectl apply --validate=false -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.crds.yaml
  post_cleanup:
  steps:
  - kubectl delete -f https://github.com/jetstack/cert-manager/releases/download/v1.3.1/cert-manager.crds.yaml
