# https://banzaicloud.com/docs/supertubes/kafka-operator/install-kafka-operator/
# Prerequisites:
# - Kubernetes 1.18.0+.
# - A Kubernetes cluster (minimum 6 vCPU and 10 GB RAM).
apiVersion: v1
kind: kbrew
app:
  repository:
    name: banzaicloud-stable
    url: https://kubernetes-charts.banzaicloud.com
    type: helm
  namespace: kafka
  sha256:
  version: 0.4.9
  pre_install:
  # Install the kafka-operator CustomResourceDefinition 
  - steps:
    - kubectl create --validate=false -f https://github.com/banzaicloud/kafka-operator/releases/download/v0.17.0/kafka-operator.crds.yaml
  post_cleanup:
    steps:
    - kubectl delete -f https://github.com/banzaicloud/kafka-operator/releases/download/v0.17.0/kafka-operator.crds.yaml
