apiVersion: v1
kind: kbrew
app:
  repository:
    name: rook-ceph-operator
    url: https://raw.githubusercontent.com/rook/rook/v1.5.8/cluster/examples/kubernetes/ceph/operator.yaml
    type: raw
  name: rook-ceph-operator
  namespace: rook-ceph
  sha256:
  version: v1.5.8
  pre_install:
  # Install CRDs and RBAC
  - steps:
    - kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.5.8/cluster/examples/kubernetes/ceph/common.yaml
    - kubectl apply -f https://raw.githubusercontent.com/rook/rook/v1.5.8/cluster/examples/kubernetes/ceph/crds.yaml
  post_cleanup:
    steps:
    - kubectl delete -f https://raw.githubusercontent.com/rook/rook/v1.5.8/cluster/examples/kubernetes/ceph/common.yaml
    - kubectl delete -f https://raw.githubusercontent.com/rook/rook/v1.5.8/cluster/examples/kubernetes/ceph/crds.yaml

